# Generated by Django 5.1.8 on 2025-06-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/users/default.avif', null=True, upload_to='images/users/'),
        ),
    ]
