# Generated by Django 5.1.8 on 2025-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/users/default.avif', upload_to='media/users/'),
        ),
    ]
