site_name: Box Buddy
site_dir: box_buddy/static/docs
use_directory_urls: false

site_url:
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        pythone:
          paths: [app]
  - glightbox
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Configuration: getting_started/configuration.md
      - Usage: getting_started/usage.md
  - Development:
      - General: dev_general.md
