# Generated by Django 5.1.8 on 2025-06-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='fake',
            field=models.BooleanField(default=False, help_text='Used for testing purposes'),
        ),
        migrations.AddField(
            model_name='file',
            name='fake',
            field=models.BooleanField(default=False, help_text='Used for testing purposes'),
        ),
        migrations.AddField(
            model_name='item',
            name='fake',
            field=models.BooleanField(default=False, help_text='Used for testing purposes'),
        ),
        migrations.AddField(
            model_name='url',
            name='fake',
            field=models.BooleanField(default=False, help_text='Used for testing purposes'),
        ),
    ]
