# Generated by Django 5.1.8 on 2025-06-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_box_fake_file_fake_item_fake_url_fake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.box'),
        ),
        migrations.AlterField(
            model_name='file',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_file', to='core.box'),
        ),
    ]
