# Generated by Django 5.1.8 on 2025-04-25 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_box_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique box'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'item', 'box', 'location'), name='unique file'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'box'), name='unique item'),
        ),
        migrations.AddConstraint(
            model_name='url',
            constraint=models.UniqueConstraint(fields=('name', 'item', 'box', 'location'), name='unique url'),
        ),
    ]
