# Generated by Django 5.1.8 on 2025-06-22 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_box_parent_alter_file_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_box', to='core.box'),
        ),
    ]
