# Generated by Django 5.1.8 on 2025-06-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_boxes', to='core.box'),
        ),
    ]
