# Generated by Django 5.1.8 on 2025-06-22 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_box_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_items', to='core.box'),
        ),
    ]
