services:
  celery_worker:
    volumes:
    - ./:/app
    - static:/app_static
    - media:/app_media
  celery_beat:
    volumes:
    - ./:/app
    - static:/app_static
    - media:/app_media
  celery_flower:
    volumes:
    - ./:/app
    - static:/app_static
    - media:/app_media
  server:
    volumes:
    - ./:/app
    - static:/app_static
    - media:/app_media
