name: mkdocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
# defaults:
#   run:
#     working-directory: ./scripts
jobs:
  deployDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"

      - name: dir
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory:"
          ls -la
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Install packages
        run: uv sync --locked --group docs

      - name: Deploy pages
        run: uv run mkdocs gh-deploy --force
